changesetIgnorePatterns:
  - '**/*.test.{js,ts,tsx}'
  - '**/*.stories.{ts,tsx}'

defaultSemverRangePrefix: ''

npmScopes:
  forecast:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN:-""}'
    npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.1.0.cjs
