name: "Move Asana Task to In Review"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  move-task-to-review:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      # TODO: Add another step in here to link the PR as a comment to the Asana task.
      #       More details here: https://github.com/marketplace/actions/asana-github-actions
      - name: Asana Github Actions
        uses: everphone-gmbh/github-asana-action@385529c13a4c0d311ac611ef4049f5a6ccf1048e
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: "move-section"
          # The space at the end of the section name is intentional - it must match the section title exactly.
          targets: '[{"project": "Current Sprint", "section": "In Review 👀 "}]'
