name: "Main"

on:
  push:
    paths:
      - "packages/**"
    branches:
      - main

jobs:
  version_or_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.x"

      # Cache Yarn dependencies
      # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Bootstrap Forecast
      - name: Install Node dependencies
        run: yarn install --immutable

      # Build Forecast
      - name: Build Forecast
        run: yarn build

      # Version or Release Forecast
      - name: Setup CI Git User
        run: |
          git config --global user.email "automaton@trueplan.io"
          git config --global user.name "trueplan-automaton"

      - name: "Creates Pull Request or Publish to npm"
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn changeset publish
          commit: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  vrt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release): version packages')"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.x"

      # Cache Yarn dependencies
      # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Bootstrap Forecast
      - name: Install Node dependencies
        run: yarn install --immutable

      # Build Forecast
      - name: Build Forecast
        run: yarn build

      # Chromatic
      - name: Build Storybook
        run: yarn build:storybook
      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: ./docs
          autoAcceptChanges: "main"
          exitOnceUploaded: true
